export interface Email {
  id: string
  sender: string
  senderEmail: string
  senderTitle: string
  senderCompany: string
  lastInteraction: string
  subject: string
  preview: string
  timestamp: string
  read: boolean
  flagged: boolean
  actionRequired: boolean
  folder: string
  body: string[]
  actions: { text: string; id: string; type: "reply" | "todo" }[]
  keyDetails: { label: string; value: string }[]
  threadSummary: string[]
  attachments: { name: string; size: string; type: string }[]
  priority: boolean
  priorityReason?: string
  isDistributionList?: boolean
}

export const folders = [
  { name: "Inbox", count: 15, key: "inbox" },
  { name: "Priority", count: 0, key: "priority" },
  { name: "Action Needed", count: 0, key: "action-needed" },
  { name: "Informational", count: 0, key: "informational" },
  { name: "Newsletters", count: 0, key: "newsletters" },
] as const

export const belowDividerFolders = [
  { name: "Sent", count: 0, key: "sent" },
  { name: "Drafts", count: 0, key: "drafts" },
] as const

export const emails: Email[] = [
  {
    id: "1",
    sender: "Marcus Chen",
    senderEmail: "m.chen@meridian.io",
    senderTitle: "VP of Operations",
    senderCompany: "Meridian Logistics",
    lastInteraction: "Feb 14, 2026",
    subject: "RE: Henderson Contract — Pallet Confirmation Needed",
    preview: "AI: Sender requests confirmation of 5-pallet order by EOD Friday",
    timestamp: "11:42 AM",
    read: false,
    flagged: true,
    actionRequired: true,
    folder: "inbox",
    body: [
      "Hi,",
      "Following up on our call yesterday regarding the Henderson contract. We need your written confirmation that you want five pallets shipped to the Newark distribution center by March 3rd.",
      "The rate we discussed was $4,200 per pallet, inclusive of insurance and handling. Total comes to $21,000. Payment terms are Net 30 from delivery date.",
      "Please confirm by end of day Friday so we can lock in the carrier slot. After that, rates may adjust due to peak season surcharges.",
      "Also, can you verify the shipping address? We have: 1847 Terminal Blvd, Unit 9C, Newark, NJ 07114.",
      "Best regards,\nMarcus Chen\nVP of Operations, Meridian Logistics"
    ],
    actions: [
      { text: "Confirm you want five pallets shipped to Newark by March 3rd", id: "a1", type: "reply" },
      { text: "Verify the shipping address: 1847 Terminal Blvd, Unit 9C, Newark, NJ 07114", id: "a2", type: "todo" },
      { text: "Respond by end of day Friday to lock carrier slot", id: "a3", type: "reply" },
    ],
    keyDetails: [
      { label: "Amount", value: "$21,000" },
      { label: "Rate", value: "$4,200/pallet" },
      { label: "Quantity", value: "5 pallets" },
      { label: "Deadline", value: "EOD Friday" },
      { label: "Delivery", value: "Mar 3, 2026" },
      { label: "Terms", value: "Net 30" },
      { label: "Destination", value: "Newark, NJ" },
    ],
    threadSummary: [
      "Henderson contract logistics discussion",
      "Marcus Chen proposed 5-pallet shipment to Newark at $4,200/pallet",
      "Rate negotiated down from $4,800",
      "Awaiting your written confirmation to finalize",
    ],
    attachments: [],
    priority: true,
    priorityReason: "Deadline approaching (EOD Friday)",
  },
  {
    id: "2",
    sender: "Sarah Okafor",
    senderEmail: "sarah@blackbirdvc.com",
    senderTitle: "Managing Partner",
    senderCompany: "Blackbird Ventures",
    lastInteraction: "Feb 13, 2026",
    subject: "Series B Term Sheet — Review Required",
    preview: "AI: Term sheet attached for $18M Series B, 72hr review window",
    timestamp: "10:15 AM",
    read: false,
    flagged: true,
    actionRequired: true,
    folder: "inbox",
    body: [
      "Good morning,",
      "As discussed, please find the term sheet for the proposed $18M Series B round attached. Key terms include a pre-money valuation of $72M, with Blackbird leading at $12M and the remaining $6M from existing investors.",
      "We have a 72-hour review window before we need to move forward with the next steps. Please loop in your legal team.",
      "Happy to jump on a call to walk through any questions.",
      "Sarah Okafor\nManaging Partner, Blackbird Ventures"
    ],
    actions: [
      { text: "Review the attached Series B term sheet ($18M round)", id: "b1", type: "todo" },
      { text: "Loop in legal team for review within 72-hour window", id: "b2", type: "todo" },
    ],
    keyDetails: [
      { label: "Round", value: "Series B" },
      { label: "Amount", value: "$18M" },
      { label: "Valuation", value: "$72M pre" },
      { label: "Lead", value: "Blackbird ($12M)" },
      { label: "Window", value: "72 hours" },
    ],
    threadSummary: [
      "Series B term sheet presented for $18M at $72M pre-money",
      "Blackbird leads with $12M, existing investors fill $6M",
      "Legal review required within 72 hours",
    ],
    attachments: [
      { name: "Series_B_Term_Sheet_v3.pdf", size: "2.4 MB", type: "pdf" },
      { name: "Cap_Table_Feb2026.xlsx", size: "156 KB", type: "spreadsheet" },
    ],
    priority: true,
    priorityReason: "72-hour review window, high-value ($18M)",
  },
  {
    id: "3",
    sender: "DevOps Bot",
    senderEmail: "alerts@infra.internal",
    senderTitle: "System",
    senderCompany: "Internal Infrastructure",
    lastInteraction: "Feb 17, 2026",
    subject: "[ALERT] Production API latency spike — p99 > 2.4s",
    preview: "AI: Production API p99 latency exceeded 2.4s threshold at 09:32 UTC",
    timestamp: "9:38 AM",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "ALERT: Production API Latency Spike",
      "Timestamp: 2026-02-17 09:32:14 UTC\nService: api-gateway-prod\nRegion: us-east-1",
      "p99 latency exceeded threshold of 2.0s, reaching 2.41s. Correlated with increased traffic from partner integration (Meridian webhook batch). Auto-scaling triggered at 09:33 UTC. Latency returned to normal (p99: 380ms) by 09:36 UTC.",
      "No action required. Monitoring continues."
    ],
    actions: [],
    keyDetails: [
      { label: "Service", value: "api-gateway-prod" },
      { label: "p99", value: "2.41s (peak)" },
      { label: "Region", value: "us-east-1" },
      { label: "Status", value: "Resolved" },
    ],
    threadSummary: [
      "Production API latency spike (p99 > 2.4s)",
      "Caused by Meridian webhook batch",
      "Auto-scaling resolved in 4 minutes",
      "No manual intervention needed",
    ],
    attachments: [],
    priority: false,
    isDistributionList: true,
  },
  {
    id: "4",
    sender: "James Whitfield",
    senderEmail: "j.whitfield@stonebridge.com",
    senderTitle: "General Counsel",
    senderCompany: "Stonebridge Legal",
    lastInteraction: "Feb 12, 2026",
    subject: "NDA Amendments — Signature Requested",
    preview: "AI: Updated NDA clauses require your signature by Feb 20",
    timestamp: "Yesterday",
    read: true,
    flagged: true,
    actionRequired: true,
    folder: "inbox",
    body: [
      "Hello,",
      "Following our negotiation, we've updated sections 4.2 (Confidentiality Period) and 7.1 (Dispute Resolution) of the mutual NDA. The confidentiality period has been extended from 2 years to 3 years, and arbitration venue has been changed to New York per your request.",
      "Please review and sign via DocuSign by February 20th.",
      "Regards,\nJames Whitfield\nGeneral Counsel, Stonebridge Legal"
    ],
    actions: [
      { text: "Review updated NDA sections 4.2 and 7.1", id: "d1", type: "todo" },
      { text: "Sign via DocuSign by February 20th", id: "d2", type: "todo" },
    ],
    keyDetails: [
      { label: "Document", value: "Mutual NDA" },
      { label: "Changes", value: "Sec 4.2, 7.1" },
      { label: "Sign By", value: "Feb 20, 2026" },
      { label: "Venue", value: "New York" },
    ],
    threadSummary: [
      "NDA amendment negotiation with Stonebridge Legal",
      "Confidentiality period extended from 2 to 3 years",
      "Arbitration venue moved to New York",
      "Final version ready for signature via DocuSign",
    ],
    attachments: [
      { name: "Mutual_NDA_Amended_v2.pdf", size: "890 KB", type: "pdf" },
    ],
    priority: true,
    priorityReason: "Signature deadline (Feb 20)",
  },
  {
    id: "5",
    sender: "Priya Mehta",
    senderEmail: "priya@qubit.design",
    senderTitle: "Creative Director",
    senderCompany: "Qubit Design Studio",
    lastInteraction: "Feb 15, 2026",
    subject: "Brand Refresh — Final Concepts Ready",
    preview: "AI: Three brand concepts ready for review in shared Figma file",
    timestamp: "Yesterday",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Hi there,",
      "The team has finalized three brand concept directions for your review. All three are available in the shared Figma file. Concept A goes bold and geometric, Concept B is more refined and minimal, and Concept C takes a hybrid approach.",
      "We'd love to schedule a 30-minute walkthrough this week if possible. Let me know your availability.",
      "Cheers,\nPriya Mehta\nCreative Director, Qubit Design Studio"
    ],
    actions: [
      { text: "Review three brand concepts in shared Figma file", id: "e1", type: "todo" },
      { text: "Schedule 30-minute walkthrough with Priya this week", id: "e2", type: "reply" },
    ],
    keyDetails: [
      { label: "Concepts", value: "3 directions" },
      { label: "Platform", value: "Figma" },
      { label: "Meeting", value: "30 min this week" },
    ],
    threadSummary: [
      "Brand refresh reached concept phase",
      "Three design directions ready for review in Figma",
      "Team requesting a 30-min walkthrough this week",
    ],
    attachments: [],
    priority: false,
  },
  {
    id: "6",
    sender: "Tom Reeves",
    senderEmail: "treeves@northpeak.co",
    senderTitle: "CEO",
    senderCompany: "NorthPeak Analytics",
    lastInteraction: "Feb 11, 2026",
    subject: "Partnership Proposal — Data Integration",
    preview: "AI: NorthPeak proposing bi-directional data sync partnership",
    timestamp: "Feb 15",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Hi,",
      "I wanted to reach out about a potential partnership between our platforms. We see a strong opportunity for a bi-directional data integration that would benefit both our user bases.",
      "Our analytics engine could provide real-time insights into your logistics data, while your distribution network data would enhance our supply chain models.",
      "Would love to set up an introductory call next week. Let me know.",
      "Tom Reeves\nCEO, NorthPeak Analytics"
    ],
    actions: [
      { text: "Consider partnership proposal for data integration", id: "f1", type: "todo" },
      { text: "Schedule introductory call with Tom next week", id: "f2", type: "reply" },
    ],
    keyDetails: [
      { label: "Company", value: "NorthPeak Analytics" },
      { label: "Type", value: "Data Partnership" },
      { label: "Integration", value: "Bi-directional" },
    ],
    threadSummary: [
      "NorthPeak proposing bi-directional data integration",
      "Their analytics engine would process your logistics data",
      "You gain access to their supply chain models",
    ],
    attachments: [
      { name: "NorthPeak_Partnership_Deck.pdf", size: "5.1 MB", type: "pdf" },
    ],
    priority: false,
  },
  {
    id: "7",
    sender: "Lisa Park",
    senderEmail: "lpark@fintechguild.org",
    senderTitle: "Events Director",
    senderCompany: "FinTech Guild",
    lastInteraction: "Feb 10, 2026",
    subject: "Speaking Slot — FinTech Summit 2026",
    preview: "AI: Invited to speak at FinTech Summit, March 18-19 in SF",
    timestamp: "Feb 14",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Hello,",
      "We'd like to invite you to speak at the FinTech Summit 2026 in San Francisco on March 18-19. We have a 25-minute keynote slot on Day 1 focused on AI in financial operations.",
      "We cover travel and accommodation. Please let us know by February 28 if you'd like to accept.",
      "Best,\nLisa Park\nEvents Director, FinTech Guild"
    ],
    actions: [
      { text: "Respond to speaking invitation by February 28", id: "g1", type: "reply" },
    ],
    keyDetails: [
      { label: "Event", value: "FinTech Summit 2026" },
      { label: "Date", value: "Mar 18-19" },
      { label: "Location", value: "San Francisco" },
      { label: "Slot", value: "25 min keynote" },
      { label: "RSVP By", value: "Feb 28" },
    ],
    threadSummary: [
      "Invited to deliver 25-min keynote at FinTech Summit 2026",
      "Topic: AI in financial operations",
      "Travel and accommodation covered",
      "RSVP needed by Feb 28",
    ],
    attachments: [],
    priority: false,
  },
  {
    id: "8",
    sender: "Elena Vasquez",
    senderEmail: "elena@clearpath.io",
    senderTitle: "Product Manager",
    senderCompany: "ClearPath Software",
    lastInteraction: "Feb 16, 2026",
    subject: "Q1 Roadmap Review — Action Items",
    preview: "AI: Q1 roadmap items need approval, 3 blockers identified",
    timestamp: "Feb 13",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Hi team,",
      "Sharing the Q1 roadmap review notes from yesterday's session. We identified 3 blockers that need executive input: the auth migration timeline, the pricing tier restructure, and the API rate limiting policy.",
      "I've tagged each item in Linear with the appropriate owners. Would appreciate your sign-off by next Tuesday so we can unblock the engineering sprints.",
      "Thanks,\nElena Vasquez\nProduct Manager, ClearPath Software"
    ],
    actions: [
      { text: "Review and approve Q1 roadmap items in Linear", id: "h1", type: "todo" },
      { text: "Provide input on 3 blockers by next Tuesday", id: "h2", type: "reply" },
    ],
    keyDetails: [
      { label: "Blockers", value: "3 items" },
      { label: "Tool", value: "Linear" },
      { label: "Deadline", value: "Next Tuesday" },
    ],
    threadSummary: [
      "Q1 roadmap review completed",
      "3 executive-level blockers identified",
      "Auth migration, pricing restructure, API rate limiting",
      "Items tagged in Linear, need sign-off by Tuesday",
    ],
    attachments: [
      { name: "Q1_Roadmap_Review_Notes.pdf", size: "340 KB", type: "pdf" },
    ],
    priority: true,
    priorityReason: "3 blockers need sign-off by Tuesday",
  },
  {
    id: "9",
    sender: "Amir Hassan",
    senderEmail: "amir@greystone.capital",
    senderTitle: "Portfolio Manager",
    senderCompany: "Greystone Capital",
    lastInteraction: "Feb 8, 2026",
    subject: "Monthly Performance Report — January 2026",
    preview: "AI: January portfolio up 3.2%, outperforming benchmark by 40bps",
    timestamp: "Feb 12",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Hi,",
      "Please find the January 2026 performance report attached. Key highlights: portfolio returned +3.2% vs benchmark +2.8%, driven primarily by overweight positions in AI infrastructure and logistics tech.",
      "Notable detractors included the energy sector allocation which was down 1.1%. We recommend reducing exposure in Q2.",
      "Happy to discuss further.",
      "Amir Hassan\nPortfolio Manager, Greystone Capital"
    ],
    actions: [],
    keyDetails: [
      { label: "Return", value: "+3.2%" },
      { label: "Benchmark", value: "+2.8%" },
      { label: "Alpha", value: "+40bps" },
      { label: "Period", value: "Jan 2026" },
    ],
    threadSummary: [
      "January 2026 portfolio performance report",
      "Portfolio returned +3.2% vs benchmark +2.8%",
      "Outperformed by 40 basis points",
      "Recommendation: reduce energy sector exposure in Q2",
    ],
    attachments: [
      { name: "Jan2026_Performance_Report.pdf", size: "1.8 MB", type: "pdf" },
      { name: "Portfolio_Breakdown.xlsx", size: "420 KB", type: "spreadsheet" },
    ],
    priority: false,
  },
  {
    id: "10",
    sender: "Rachel Kim",
    senderEmail: "rachel@bridgecomm.co",
    senderTitle: "Account Executive",
    senderCompany: "BridgeComm",
    lastInteraction: "Feb 7, 2026",
    subject: "Invoice #BC-2026-0142 — Payment Reminder",
    preview: "AI: Outstanding invoice for $8,750, due Feb 22",
    timestamp: "Feb 11",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Hi,",
      "This is a friendly reminder that Invoice #BC-2026-0142 for $8,750 is due on February 22, 2026. This covers the January communication platform subscription and the additional seat licenses we provisioned.",
      "Payment can be made via ACH or wire transfer. Details are on the invoice.",
      "Let me know if you have any questions.",
      "Rachel Kim\nAccount Executive, BridgeComm"
    ],
    actions: [
      { text: "Process payment of $8,750 for Invoice #BC-2026-0142 by Feb 22", id: "j1", type: "todo" },
    ],
    keyDetails: [
      { label: "Invoice", value: "#BC-2026-0142" },
      { label: "Amount", value: "$8,750" },
      { label: "Due", value: "Feb 22, 2026" },
      { label: "Method", value: "ACH / Wire" },
    ],
    threadSummary: [
      "Payment reminder from BridgeComm",
      "January subscription + additional seat licenses",
      "Invoice: $8,750 due February 22",
      "Payment via ACH or wire transfer",
    ],
    attachments: [
      { name: "Invoice_BC-2026-0142.pdf", size: "92 KB", type: "pdf" },
    ],
    priority: true,
    priorityReason: "Payment due soon (Feb 22)",
  },

  // === SENT EMAILS ===
  {
    id: "11",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 18, 2026",
    subject: "RE: Partnership Proposal — Data Integration",
    preview: "Sent reply to Tom Reeves about scheduling a call next week",
    timestamp: "10:30 AM",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "sent",
    body: [
      "Hi Tom,",
      "Thanks for reaching out. The bi-directional data integration concept is interesting and aligns with our roadmap. I'd like to explore this further.",
      "Let's set up a call next week. I'm available Tuesday or Wednesday afternoon. Can you send over a more detailed technical spec beforehand so my engineering team can review?",
      "Looking forward to it.",
      "Best"
    ],
    actions: [
      { text: "Follow up with Tom Reeves if no reply by Wednesday", id: "s1a", type: "todo" },
      { text: "Ask engineering to review NorthPeak technical spec when received", id: "s1b", type: "todo" },
    ],
    keyDetails: [
      { label: "To", value: "Tom Reeves" },
      { label: "Re", value: "Partnership Proposal" },
      { label: "Next Step", value: "Call Tue/Wed" },
    ],
    threadSummary: [
      "You replied positively to NorthPeak partnership proposal",
      "Requested a call next week (Tue/Wed)",
      "Asked for detailed technical spec for engineering review",
    ],
    attachments: [],
    priority: false,
  },
  {
    id: "12",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 17, 2026",
    subject: "RE: Series B Term Sheet — Review Required",
    preview: "Sent acknowledgment to Sarah, looped in legal team",
    timestamp: "2:15 PM",
    read: true,
    flagged: true,
    actionRequired: false,
    folder: "sent",
    body: [
      "Hi Sarah,",
      "Thank you for sending over the term sheet. I've reviewed the headline numbers and they're in the right ballpark. I've cc'd our counsel James Whitfield to begin the formal legal review.",
      "Can we schedule a call for Thursday to walk through the governance provisions and board composition? I have a few questions on the liquidation preference structure.",
      "Thanks,",
    ],
    actions: [
      { text: "Follow up with Sarah Okafor on Thursday call scheduling", id: "s2a", type: "todo" },
      { text: "Follow up with James Whitfield on term sheet legal review progress", id: "s2b", type: "todo" },
      { text: "Prepare questions on liquidation preference structure before Thursday call", id: "s2c", type: "todo" },
    ],
    keyDetails: [
      { label: "To", value: "Sarah Okafor" },
      { label: "CC", value: "James Whitfield" },
      { label: "Re", value: "Series B Term Sheet" },
      { label: "Next Step", value: "Call Thursday" },
    ],
    threadSummary: [
      "You acknowledged receipt of Series B term sheet",
      "Looped in legal counsel (James Whitfield)",
      "Requested call Thursday for governance and board composition",
      "Questions about liquidation preference structure pending",
    ],
    attachments: [],
    priority: true,
    priorityReason: "Follow up on $18M Series B term sheet",
  },
  {
    id: "13",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 16, 2026",
    subject: "Vendor Evaluation — Warehouse Management Systems",
    preview: "Sent RFP to three WMS vendors for Q2 evaluation",
    timestamp: "Yesterday",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "sent",
    body: [
      "Hi all,",
      "As discussed in last week's ops meeting, I'm kicking off the WMS vendor evaluation. Attached is the RFP document outlining our requirements for the warehouse management system upgrade.",
      "We're evaluating three vendors: LogiFlow, WarePro, and ShelfSmart. I'd like initial proposals back by March 1st so we can schedule demos during the first week of March.",
      "Please reach out with any questions about the requirements.",
      "Best"
    ],
    actions: [
      { text: "Follow up with LogiFlow, WarePro, and ShelfSmart if proposals not received by Feb 28", id: "s3a", type: "todo" },
      { text: "Schedule WMS demos for first week of March", id: "s3b", type: "todo" },
    ],
    keyDetails: [
      { label: "To", value: "3 WMS Vendors" },
      { label: "Re", value: "RFP - WMS Upgrade" },
      { label: "Proposals Due", value: "Mar 1" },
      { label: "Demos", value: "First week Mar" },
    ],
    threadSummary: [
      "You sent RFP to three WMS vendors",
      "Evaluating LogiFlow, WarePro, and ShelfSmart",
      "Proposals due March 1st, demos first week of March",
    ],
    attachments: [
      { name: "WMS_RFP_2026.pdf", size: "1.2 MB", type: "pdf" },
    ],
    priority: false,
  },
  {
    id: "14",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 15, 2026",
    subject: "RE: Q1 Roadmap Review — Action Items",
    preview: "Sent approval for auth migration, requested more data on pricing tiers",
    timestamp: "Feb 15",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "sent",
    body: [
      "Hi Elena,",
      "Thanks for pulling this together. Here's my input on the three blockers:",
      "1. Auth migration: Approved. Let's target end of March for completion. Make sure we have a rollback plan.",
      "2. Pricing tier restructure: I need to see the revenue impact analysis before signing off. Can you pull the numbers from Stripe for the last 6 months?",
      "3. API rate limiting: Let's go with the tiered approach (100/min free, 1000/min pro, unlimited enterprise). Engineering can proceed.",
      "Let me know if you need anything else.",
    ],
    actions: [
      { text: "Follow up with Elena on pricing tier revenue impact analysis", id: "s4a", type: "todo" },
      { text: "Check auth migration rollback plan when ready", id: "s4b", type: "todo" },
    ],
    keyDetails: [
      { label: "To", value: "Elena Vasquez" },
      { label: "Re", value: "Q1 Roadmap Blockers" },
      { label: "Auth", value: "Approved (Mar)" },
      { label: "Pricing", value: "Need data" },
      { label: "Rate Limit", value: "Approved" },
    ],
    threadSummary: [
      "You approved auth migration and API rate limiting",
      "Requested revenue impact data for pricing tier decision",
      "Auth migration targets end of March with rollback plan",
    ],
    attachments: [],
    priority: false,
  },
  {
    id: "15",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 14, 2026",
    subject: "Intro: Daniel Fry <> Priya Mehta — Brand Work",
    preview: "Sent warm intro connecting Daniel with Priya for brand consultation",
    timestamp: "Feb 14",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "sent",
    body: [
      "Hi Daniel, Priya,",
      "Connecting you two. Daniel — Priya runs Qubit Design Studio and has been leading our brand refresh. Priya — Daniel is our Head of Growth and will be your main point of contact for anything customer-facing.",
      "I'll leave you two to coordinate from here.",
      "Best"
    ],
    actions: [
      { text: "Check in with Daniel and Priya on brand handoff progress next week", id: "s5a", type: "todo" },
    ],
    keyDetails: [
      { label: "To", value: "Daniel Fry, Priya Mehta" },
      { label: "Re", value: "Brand refresh handoff" },
    ],
    threadSummary: [
      "You introduced Daniel Fry (Head of Growth) to Priya Mehta (Qubit Design)",
      "Brand refresh work being handed off to Daniel as main contact",
    ],
    attachments: [],
    priority: false,
  },
  {
    id: "16",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 13, 2026",
    subject: "RE: Speaking Slot — FinTech Summit 2026",
    preview: "Accepted speaking invitation, requested topic brief",
    timestamp: "Feb 13",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "sent",
    body: [
      "Hi Lisa,",
      "I'd be happy to accept the keynote slot at FinTech Summit. AI in financial operations is right in our wheelhouse.",
      "Could you send over a brief on the expected audience and any specific angles you'd like me to cover? I'll start working on the deck.",
      "Also, please send travel/accommodation details when available.",
      "Thanks,"
    ],
    actions: [
      { text: "Follow up with Lisa Park for audience brief and travel details", id: "s6a", type: "todo" },
      { text: "Start preparing FinTech Summit keynote deck", id: "s6b", type: "todo" },
    ],
    keyDetails: [
      { label: "To", value: "Lisa Park" },
      { label: "Re", value: "FinTech Summit keynote" },
      { label: "Status", value: "Accepted" },
      { label: "Next", value: "Audience brief, deck prep" },
    ],
    threadSummary: [
      "You accepted the FinTech Summit keynote invitation",
      "Requested audience brief and specific angle guidance",
      "Will start preparing presentation deck",
    ],
    attachments: [],
    priority: false,
  },

  // === MORE INBOX EMAILS ===
  {
    id: "17",
    sender: "Daniel Fry",
    senderEmail: "d.fry@openfield.app",
    senderTitle: "Head of Growth",
    senderCompany: "OpenField",
    lastInteraction: "Feb 18, 2026",
    subject: "Customer Churn Report — February Update",
    preview: "AI: Monthly churn down to 2.1%, but enterprise segment needs attention",
    timestamp: "9:05 AM",
    read: false,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Hey,",
      "February churn report is in. Good news: overall churn is down to 2.1% from 2.8% in January. The onboarding flow changes we made last month are clearly working for SMB customers.",
      "However, enterprise churn ticked up to 3.4%. I dug in and it looks like we lost two mid-market accounts (Coastal Freight and DataBridge) citing integration issues with their ERP systems.",
      "I think we need to prioritize the ERP integration work. Can we discuss in the leadership sync tomorrow?",
      "— Daniel"
    ],
    actions: [
      { text: "Discuss ERP integration priority at leadership sync tomorrow", id: "k1", type: "todo" },
    ],
    keyDetails: [
      { label: "Overall Churn", value: "2.1% (down)" },
      { label: "Enterprise Churn", value: "3.4% (up)" },
      { label: "Lost Accounts", value: "2 mid-market" },
      { label: "Root Cause", value: "ERP integration" },
    ],
    threadSummary: [
      "February churn report: overall down to 2.1%",
      "Enterprise churn up to 3.4%, lost two mid-market accounts",
      "ERP integration issues driving enterprise losses",
    ],
    attachments: [
      { name: "Feb_Churn_Report.pdf", size: "780 KB", type: "pdf" },
    ],
    priority: true,
    priorityReason: "Enterprise churn spike needs attention",
  },
  {
    id: "18",
    sender: "Maya Rodriguez",
    senderEmail: "maya@greenline.co",
    senderTitle: "Sustainability Lead",
    senderCompany: "GreenLine Logistics",
    lastInteraction: "Feb 17, 2026",
    subject: "Carbon Offset Program — Proposal for OpenField",
    preview: "AI: Proposing carbon offset integration for logistics operations",
    timestamp: "8:20 AM",
    read: false,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Hello,",
      "GreenLine helps logistics companies offset their carbon footprint through verified carbon credit programs. Based on your shipping volume, we estimate your annual carbon output at approximately 2,400 metric tons.",
      "We'd like to propose a tailored offset program that integrates directly with your platform. Costs range from $12-18 per metric ton depending on the verification standard.",
      "Would you be open to a 20-minute intro call?",
      "Maya Rodriguez\nSustainability Lead, GreenLine Logistics"
    ],
    actions: [],
    keyDetails: [
      { label: "Company", value: "GreenLine Logistics" },
      { label: "Est. Carbon", value: "2,400 MT/yr" },
      { label: "Cost", value: "$12-18/MT" },
    ],
    threadSummary: [
      "GreenLine proposing carbon offset program for OpenField",
      "Estimated 2,400 metric tons annual carbon output",
      "Integration would work directly with your platform",
    ],
    attachments: [
      { name: "GreenLine_Proposal.pdf", size: "3.2 MB", type: "pdf" },
    ],
    priority: false,
  },
  {
    id: "19",
    sender: "HR System",
    senderEmail: "hr@openfield.app",
    senderTitle: "System",
    senderCompany: "OpenField",
    lastInteraction: "Feb 18, 2026",
    subject: "New Hire Onboarding — Week of Feb 24",
    preview: "AI: 3 new hires starting next week, onboarding schedule attached",
    timestamp: "8:00 AM",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Onboarding Notification",
      "Three new team members are starting the week of February 24th:",
      "1. Sofia Nguyen — Senior Backend Engineer (Elena's team)\n2. Marcus Webb — Sales Development Rep (Daniel's team)\n3. Ana Petrov — Data Analyst (Analytics team)",
      "Onboarding schedule and buddy assignments are attached. Please ensure IT access is provisioned by Friday Feb 21.",
    ],
    actions: [
      { text: "Ensure IT access provisioned for 3 new hires by Friday Feb 21", id: "m1", type: "todo" },
    ],
    keyDetails: [
      { label: "New Hires", value: "3 people" },
      { label: "Start Date", value: "Week of Feb 24" },
      { label: "IT Deadline", value: "Feb 21" },
    ],
    threadSummary: [
      "3 new hires starting week of Feb 24",
      "Backend engineer, sales rep, and data analyst",
      "IT access needs provisioning by Feb 21",
    ],
    attachments: [
      { name: "Onboarding_Schedule_Feb24.pdf", size: "156 KB", type: "pdf" },
    ],
    priority: false,
    isDistributionList: true,
  },
  {
    id: "20",
    sender: "Carlos Mendez",
    senderEmail: "carlos@atlasfreight.com",
    senderTitle: "Operations Director",
    senderCompany: "Atlas Freight Corp",
    lastInteraction: "Feb 16, 2026",
    subject: "RE: API Integration — Status Update",
    preview: "AI: Atlas Freight API integration delayed 2 weeks, blocker on auth module",
    timestamp: "Feb 16",
    read: true,
    flagged: true,
    actionRequired: true,
    folder: "inbox",
    body: [
      "Hi,",
      "Quick update on the API integration. We've hit a blocker on our auth module — our security team flagged a concern with the OAuth flow. They want to switch to mTLS.",
      "This pushes our timeline out by about 2 weeks. New target go-live date is March 14 instead of March 1.",
      "I know this impacts your Q1 targets. Happy to jump on a call to discuss alternatives.",
      "Carlos Mendez\nOperations Director, Atlas Freight Corp"
    ],
    actions: [
      { text: "Discuss Atlas Freight API delay with engineering team", id: "n1", type: "todo" },
      { text: "Schedule call with Carlos to discuss mTLS vs OAuth alternatives", id: "n2", type: "reply" },
    ],
    keyDetails: [
      { label: "Blocker", value: "Auth module (OAuth)" },
      { label: "Proposed Fix", value: "Switch to mTLS" },
      { label: "Delay", value: "2 weeks" },
      { label: "New Go-Live", value: "Mar 14" },
    ],
    threadSummary: [
      "Atlas Freight API integration delayed by 2 weeks",
      "Blocker: security team flagged OAuth flow, wants mTLS",
      "New target go-live: March 14 instead of March 1",
      "Impacts Q1 integration targets",
    ],
    attachments: [],
    priority: true,
    priorityReason: "Integration delay impacts Q1 targets",
  },
  {
    id: "21",
    sender: "Booking.com",
    senderEmail: "noreply@booking.com",
    senderTitle: "System",
    senderCompany: "Booking.com",
    lastInteraction: "Feb 18, 2026",
    subject: "Booking Confirmation — San Francisco, Mar 17-20",
    preview: "AI: Hotel booking confirmed for FinTech Summit trip",
    timestamp: "7:30 AM",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "inbox",
    body: [
      "Booking Confirmed",
      "Hotel: The Marker San Francisco\nCheck-in: March 17, 2026 (3:00 PM)\nCheck-out: March 20, 2026 (11:00 AM)\n3 nights — King Room, City View",
      "Confirmation #: BK-7829451\nTotal: $1,247.00 (prepaid)",
      "You can manage your booking at booking.com/manage"
    ],
    actions: [],
    keyDetails: [
      { label: "Hotel", value: "The Marker SF" },
      { label: "Dates", value: "Mar 17-20" },
      { label: "Conf #", value: "BK-7829451" },
      { label: "Total", value: "$1,247.00" },
    ],
    threadSummary: [
      "Hotel booking confirmed for FinTech Summit trip",
      "The Marker San Francisco, March 17-20",
      "3 nights, King Room, $1,247 prepaid",
    ],
    attachments: [],
    priority: false,
    isDistributionList: true,
  },

  // === MORE SENT ===
  {
    id: "22",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 17, 2026",
    subject: "RE: API Integration — Status Update",
    preview: "Sent reply to Carlos requesting mTLS technical details",
    timestamp: "Feb 17",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "sent",
    body: [
      "Hi Carlos,",
      "Thanks for the heads up. Two-week delay is manageable but let's make sure we don't slip further.",
      "Can your security team send over the mTLS requirements doc? I'll loop in our infra team so we can start parallel work on our end. No reason we can't meet the March 14 date if we start now.",
      "Let's do a joint standup on Mondays until go-live to keep things on track.",
      "Best"
    ],
    actions: [
      { text: "Follow up with Carlos on mTLS requirements doc", id: "s7a", type: "todo" },
      { text: "Set up Monday standups with Atlas Freight until go-live", id: "s7b", type: "todo" },
      { text: "Brief infra team on mTLS integration requirement", id: "s7c", type: "todo" },
    ],
    keyDetails: [
      { label: "To", value: "Carlos Mendez" },
      { label: "Re", value: "API Integration Delay" },
      { label: "Action", value: "mTLS parallel work" },
      { label: "Cadence", value: "Monday standups" },
    ],
    threadSummary: [
      "You replied to Atlas Freight API delay",
      "Requested mTLS requirements doc for parallel engineering work",
      "Proposed weekly Monday standups until March 14 go-live",
    ],
    attachments: [],
    priority: false,
  },
  {
    id: "23",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 16, 2026",
    subject: "Board Update — February 2026",
    preview: "Monthly board update with metrics, hiring, and fundraise status",
    timestamp: "Feb 16",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "sent",
    body: [
      "Hi Board,",
      "February update below. Key highlights:",
      "Revenue: $842K MRR (+8% MoM)\nBurn: $310K/mo (18 months runway)\nHeadcount: 47 (3 new hires starting Feb 24)\nChurn: 2.1% overall, 3.4% enterprise (investigating)",
      "Fundraise: Series B term sheet received from Blackbird Ventures ($18M at $72M pre). Legal review in progress.",
      "Key risks: Enterprise churn uptick, Atlas Freight integration delay.",
      "Happy to discuss any of this in our next board call.",
      "Best"
    ],
    actions: [
      { text: "Prepare for board call — expect questions on enterprise churn", id: "s8a", type: "todo" },
    ],
    keyDetails: [
      { label: "To", value: "Board of Directors" },
      { label: "MRR", value: "$842K (+8%)" },
      { label: "Burn", value: "$310K/mo" },
      { label: "Runway", value: "18 months" },
      { label: "Headcount", value: "47" },
    ],
    threadSummary: [
      "Monthly board update sent for February 2026",
      "MRR at $842K, growing 8% MoM",
      "Series B term sheet in legal review",
      "Flagged enterprise churn and Atlas Freight delay as risks",
    ],
    attachments: [
      { name: "Board_Update_Feb2026.pdf", size: "2.1 MB", type: "pdf" },
      { name: "Metrics_Dashboard_Feb.pdf", size: "950 KB", type: "pdf" },
    ],
    priority: false,
  },
  {
    id: "24",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 14, 2026",
    subject: "Candidate Follow-Up — VP Engineering Role",
    preview: "Sent follow-up to VP Eng candidate after final round interview",
    timestamp: "Feb 14",
    read: true,
    flagged: true,
    actionRequired: false,
    folder: "sent",
    body: [
      "Hi Kenji,",
      "Thank you for taking the time to go through our final round yesterday. The team was really impressed by your systems design approach and your experience scaling engineering orgs from 20 to 100+.",
      "I'd like to move forward with an offer. My head of people, Dana, will be reaching out this week with the details. In the meantime, happy to answer any questions.",
      "Really hope we can make this work.",
      "Best"
    ],
    actions: [
      { text: "Follow up with Dana on VP Engineering offer package for Kenji", id: "s9a", type: "todo" },
      { text: "Follow up with Kenji if no response by Friday", id: "s9b", type: "todo" },
    ],
    keyDetails: [
      { label: "To", value: "Kenji Nakamura" },
      { label: "Re", value: "VP Engineering Offer" },
      { label: "Status", value: "Moving to offer" },
      { label: "Next Step", value: "Dana sends package" },
    ],
    threadSummary: [
      "You sent positive follow-up after VP Eng final round",
      "Moving to offer stage, Dana handling package details",
      "Candidate: Kenji Nakamura, experienced in scaling eng orgs",
    ],
    attachments: [],
    priority: true,
    priorityReason: "Key hire — VP Engineering offer pending",
  },

  // === DRAFTS ===
  {
    id: "25",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 18, 2026",
    subject: "RE: Carbon Offset Program — Proposal for OpenField",
    preview: "Draft reply to GreenLine — requesting pilot program details",
    timestamp: "Draft",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "drafts",
    body: [
      "Hi Maya,",
      "Thanks for the proposal. The carbon offset integration is interesting and could be a differentiator for us with enterprise customers who have sustainability mandates.",
      "Before we commit to a full program, would you be open to a pilot? Maybe we could start with one region and measure impact over 90 days.",
      "[TODO: Add specific region suggestion and budget range]",
    ],
    actions: [],
    keyDetails: [
      { label: "To", value: "Maya Rodriguez" },
      { label: "Status", value: "Draft" },
    ],
    threadSummary: [
      "Draft reply to GreenLine carbon offset proposal",
      "Proposing a pilot program before full commitment",
    ],
    attachments: [],
    priority: false,
  },
  {
    id: "26",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 17, 2026",
    subject: "Customer Advisory Board — Q2 Invitations",
    preview: "Draft invitation for customer advisory board members",
    timestamp: "Draft",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "drafts",
    body: [
      "Hi [Name],",
      "I'm writing to invite you to join OpenField's Customer Advisory Board for Q2 2026. As one of our most valued customers, your input would be invaluable in shaping our product roadmap.",
      "The commitment is one 60-minute virtual session per month (April, May, June). In return, you'll get early access to new features and a direct line to our product team.",
      "[TODO: Finalize incentive package and list of invitees]",
    ],
    actions: [],
    keyDetails: [
      { label: "Status", value: "Draft" },
      { label: "Cadence", value: "Monthly, 60 min" },
      { label: "Period", value: "Q2 2026" },
    ],
    threadSummary: [
      "Draft invitation for Q2 Customer Advisory Board",
      "Monthly 60-min sessions with early feature access",
    ],
    attachments: [],
    priority: false,
  },
  {
    id: "27",
    sender: "You",
    senderEmail: "me@openfield.app",
    senderTitle: "Founder",
    senderCompany: "OpenField",
    lastInteraction: "Feb 15, 2026",
    subject: "RE: Henderson Contract — Pallet Confirmation",
    preview: "Draft confirmation to Marcus for 5-pallet shipment",
    timestamp: "Draft",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "drafts",
    body: [
      "Hi Marcus,",
      "This email serves as written confirmation for the following order:",
      "Quantity: 5 pallets\nDestination: 1847 Terminal Blvd, Unit 9C, Newark, NJ 07114\nDelivery Date: March 3, 2026\nRate: $4,200 per pallet\nTotal: $21,000\nPayment Terms: Net 30",
      "[TODO: Verify shipping address with warehouse team before sending]",
    ],
    actions: [],
    keyDetails: [
      { label: "To", value: "Marcus Chen" },
      { label: "Status", value: "Draft" },
      { label: "Total", value: "$21,000" },
    ],
    threadSummary: [
      "Draft confirmation for Henderson contract pallet order",
      "5 pallets to Newark, $21K total",
      "Needs shipping address verification before sending",
    ],
    attachments: [],
    priority: false,
  },

  // === ARCHIVED ===
  {
    id: "28",
    sender: "AWS",
    senderEmail: "no-reply@aws.amazon.com",
    senderTitle: "System",
    senderCompany: "Amazon Web Services",
    lastInteraction: "Feb 5, 2026",
    subject: "Your January 2026 AWS Bill is Available",
    preview: "AI: January AWS bill: $14,280.00",
    timestamp: "Feb 5",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "archived",
    body: [
      "Your January 2026 bill is now available.",
      "Total: $14,280.00\nAccount: 4729-8813-2244\nPayment Method: Visa ending 4821",
      "View detailed breakdown at console.aws.amazon.com/billing",
    ],
    actions: [],
    keyDetails: [
      { label: "Amount", value: "$14,280" },
      { label: "Period", value: "January 2026" },
    ],
    threadSummary: [
      "Monthly AWS bill for January 2026",
      "Total: $14,280, auto-payment via Visa",
    ],
    attachments: [],
    priority: false,
    isDistributionList: true,
  },
  {
    id: "29",
    sender: "LinkedIn",
    senderEmail: "messages-noreply@linkedin.com",
    senderTitle: "System",
    senderCompany: "LinkedIn",
    lastInteraction: "Feb 3, 2026",
    subject: "5 new connection requests",
    preview: "AI: Weekly LinkedIn connection digest",
    timestamp: "Feb 3",
    read: true,
    flagged: false,
    actionRequired: false,
    folder: "archived",
    body: [
      "You have 5 new connection requests this week.",
      "Review and accept at linkedin.com/mynetwork",
    ],
    actions: [],
    keyDetails: [],
    threadSummary: ["Weekly LinkedIn connection request digest"],
    attachments: [],
    priority: false,
    isDistributionList: true,
  },
]
